### ISSUE TITLE
Getting the dataset

### ISSUE THREAD

**Issue by akshaybahadur21** [harish988/AVENGERS#1]
@Vivek0712 @harish988 
Great work guys.
Normally, the first step is Problem statement and that looks being taken care of.
So now let's move onto some coding aspect.
Now, I want you to ditch what you guys have done till now. It's good but I can see that it is not production ready.
What I would like you guys to do is follow a prototype-approach where we can implement small features quickly so that we can have a small workable demo at the end of every week or 2 weeks.

    Step 1 : Getting the dataset.

I can see that you have the dataset with you. You can elaborate a bit on the dataset that you guys are using along with sample images for documentation purposes.
PS - You should ask me questions in case of any doubt.

**Comment by Vivek0712** [comment]
Acknowledged

**Comment by Vivek0712** [comment]
https://github.com/harish988/AVENGERS/tree/master/Dataset

Dataset has been uploaded. Please look into it

**Comment by akshaybahadur21** [comment]
@Vivek0712 @harish988 - Kindly tag me before closing the issues
