### ISSUE TITLE
Preprocessing and Model outline

### ISSUE THREAD

**Issue by akshaybahadur21** [harish988/AVENGERS#3]
@Vivek0712 @harish988 @anamalaii @HariharanShanmugam 
Great work until now guys.
I hope you guys have a good idea of how to proceed forward.
You guys can divide the work for model creation and processing.
Few things to keep in mind

- Model robustness
- Preprocessing
- Explainable AI [Dipanjan's repo](https://github.com/dipanjanS/explainable_artificial_intelligence)

PS : You guys can ask me questions at any time.

**Comment by Vivek0712** [comment]
Hi @akshaybahadur21 ,
The code for the Model training and visualization can be found here:
https://github.com/harish988/AVENGERS/blob/master/Preprocessing%2C_Model_Training_and_Vizualization.ipynb
